version: "3.8"
services:
  app:
    build:
      context: app/
    restart: always
    ports:
      - "${EXT_PORT_APP}:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public
      - PORT_APP=3000
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH_USERNAME=${SMTP_AUTH_USERNAME}
      - SMTP_AUTH_PASSWORD=${SMTP_AUTH_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - FILE_UPLOAD_PATH=${FILE_UPLOAD_PATH}
    volumes:
      - ${EXT_FILE_UPLOAD_PATH}:/app/files
    networks:
      - private
    links:
      - "db:db"

  db:
    image: ankane/pgvector:v0.4.4
    restart: always
    ports:
      - "${EXT_PORT_DB}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private

volumes:
  db-data:

networks:
  private: {}
